version : "3.8"

services:
  # pg_db_production:
  #   image: postgres:latest
  #   container_name: pg_db_prod
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: admin
  #   volumes:
  #     - ./data-prod:/var/lib/postgresql/data
  #   ports:
  #     - 5431:5432
  

  pg_db_development:
    image: postgres:latest
    container_name: pg_db_dev
    volumes:
      - ./data/data-dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      # POSTGRES_DB: inventory-test
    ports:
      - "5433:5432"

  pg_db_test:
    image: postgres:latest
    container_name: pg_db_test
    volumes:
      - ./data/data-test:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      # POSTGRES_DB: inventory-test
    ports:
      - "5434:5432"